(function(){
  "use strict";
  var boot=window.__WORKSPACE__||{};
  var state={data:null,loadedViews:{overview:true}};
  var shell=document.querySelector(".workspace-shell");
  var role=boot.role||document.documentElement.getAttribute("data-workspace-role")||"";

  function text(value){return value===undefined||value===null?"":String(value);}
  function escapeHtml(value){var node=document.createElement("span");node.textContent=text(value);return node.innerHTML;}
  function showToast(message){var node=document.getElementById("toast");node.textContent=message;node.hidden=false;window.clearTimeout(showToast.timer);showToast.timer=window.setTimeout(function(){node.hidden=true;},2600);}
  function empty(label,detail){return '<div class="empty-state"><div><strong>'+escapeHtml(label)+'</strong><p>'+escapeHtml(detail)+'</p></div></div>';}
  async function request(url,options){
    var response=await fetch(url,Object.assign({credentials:"same-origin",headers:{"content-type":"application/json"}},options||{}));
    if(response.status===401){window.location.assign("/login");throw new Error("登录状态已失效");}
    var payload=await response.json().catch(function(){return {};});
    if(!response.ok||!payload.success){throw new Error(((payload||{}).error||{}).message||"请求失败");}
    return payload.content;
  }
  function roleVisibility(){
    document.querySelectorAll("[data-admin-only]").forEach(function(node){node.hidden=role!=="admin";});
    document.querySelectorAll("[data-teacher-only]").forEach(function(node){node.hidden=role!=="teacher";});
  }
  function metricDefinitions(){return role==="admin"?[
    ["teachers","教师账号","人","在职与停用账号"],["activeClasses","在读班级","个","当前授课班级"],["students","在读学员","人","已纳入教学管理"],["todayLessons","今日课程","节","当天教学安排"]
  ]:[
    ["classes","我的班级","个","仅显示本人授课班级"],["todayLessons","今日课程","节","可直接进入课堂"],["pendingPreparation","待备课程","节","尚未关联备课内容"]
  ];}
  function renderMetrics(metrics){
    document.getElementById("metric-grid").innerHTML=metricDefinitions().map(function(item){return '<div class="metric"><span class="metric-label">'+item[1]+'</span><strong class="metric-value">'+escapeHtml(metrics[item[0]]||0)+' <small>'+item[2]+'</small></strong><span class="metric-note">'+item[3]+'</span></div>';}).join("");
  }
  function renderLessons(rows){
    var node=document.getElementById("today-lessons");
    if(!rows||!rows.length){node.innerHTML=empty("今日暂无课程","新的排课会在这里显示。");return;}
    node.className="";node.innerHTML=rows.map(function(row){var start=text(row.startTime).slice(11,16)||"待定";var href=row.materialId?"/code-classroom/teach-lessons/lessons/ppt?curriculumMaterial_id="+encodeURIComponent(row.materialId)+"&teaching_plan_id="+encodeURIComponent(row.id):"/code-classroom/classroom-index";return '<div class="lesson-row"><span class="lesson-time">'+escapeHtml(start)+'</span><div><div class="row-title">'+escapeHtml(row.title||row.className||"课程教学")+'</div><div class="row-meta">'+escapeHtml(row.className||"班级待确认")+'</div></div><a class="row-link" href="'+href+'">进入课堂</a></div>';}).join("");
  }
  function renderClasses(rows){var node=document.getElementById("teacher-classes");if(!node)return;if(!rows||!rows.length){node.innerHTML=empty("暂无授课班级","管理员完成班级分配后会显示在这里。");return;}node.className="";node.innerHTML=rows.map(function(row){return '<div class="class-row"><span class="lesson-time">'+escapeHtml(row.time_str||"待排课")+'</span><div><div class="row-title">'+escapeHtml(row.name||row.className||"未命名班级")+'</div><div class="row-meta">'+escapeHtml(row.campusName||"")+'</div></div><a class="row-link" href="/code-classroom/classroom-index">进入班级</a></div>';}).join("");}
  function renderExceptions(rows){var node=document.getElementById("exceptions");if(!node)return;if(!rows||!rows.length){node.innerHTML=empty("暂无待处理事项","关键教学配置均已就绪。");return;}node.className="";node.innerHTML=rows.map(function(row){return '<div class="exception-row"><span class="exception-mark"></span><div><div class="row-title">'+escapeHtml(row.label)+'</div><div class="row-meta">班级尚未分配主讲教师</div></div><a class="row-link" href="'+escapeHtml(row.href)+'">处理</a></div>';}).join("");}
  function renderWorkspace(data){state.data=data;document.getElementById("school-name").textContent=data.schoolName||"教学机构";document.getElementById("account-name").textContent=data.displayName||"当前用户";document.getElementById("account-avatar").textContent=(data.displayName||"L").slice(0,1).toUpperCase();document.getElementById("today-label").textContent=new Intl.DateTimeFormat("zh-CN",{month:"long",day:"numeric",weekday:"long"}).format(new Date());document.getElementById("welcome-copy").textContent=role==="admin"?"集中查看机构教学运行状态并处理关键事项。":"查看今日课程、本人班级与备课进度。";renderMetrics(data.metrics||{});renderLessons(data.todayLessons||[]);renderClasses(data.classes||[]);renderExceptions(data.exceptions||[]);}
  function renderLoadError(error){document.getElementById("metric-grid").innerHTML=empty("数据加载失败",error.message||"请稍后重试");document.getElementById("today-lessons").innerHTML=empty("无法读取课程","刷新页面后重试。");}
  function openView(key){
    if(role!=="admin"&&(key==="teachers"||key==="campuses")){return;}
    document.querySelectorAll(".view").forEach(function(view){view.classList.toggle("is-active",view.getAttribute("data-view")===key);});
    document.querySelectorAll(".nav-link").forEach(function(link){link.classList.toggle("is-active",link.getAttribute("data-nav-key")===key||(key==="overview"&&link.getAttribute("data-nav-key")==="overview"));});
    shell.classList.remove("menu-open");
    if(!state.loadedViews[key]){state.loadedViews[key]=true;document.dispatchEvent(new CustomEvent("workspace:view",{detail:{view:key}}));}
  }
  function initialView(){var key=(location.hash||"").replace(/^#/,"");return key==="teachers"||key==="campuses"?key:"overview";}
  function field(name,label,value,type,full,options){
    var control="";
    if(options){control='<select name="'+name+'">'+options.map(function(option){return '<option value="'+escapeHtml(option.value)+'"'+(String(option.value)===String(value)?' selected':'')+'>'+escapeHtml(option.label)+'</option>';}).join("")+'</select>';}
    else{control='<input name="'+name+'" type="'+(type||"text")+'" value="'+escapeHtml(value||"")+'" '+(name==="name"?'required':'')+'>';}
    return '<div class="field'+(full?' full':'')+'"><label>'+escapeHtml(label)+'</label>'+control+'</div>';
  }
  function openRecordDialog(mode,title,kicker,fields,record){var dialog=document.getElementById("record-dialog");state.dialog={mode:mode,record:record||{}};document.getElementById("dialog-title").textContent=title;document.getElementById("dialog-kicker").textContent=kicker;document.getElementById("dialog-fields").innerHTML=fields;document.getElementById("dialog-error").textContent="";dialog.showModal();}
  function campusOptions(selected){var rows=(state.data&&state.data.campuses)||[];var options=[{value:"",label:"请选择校区"}];rows.forEach(function(row){options.push({value:row.id,label:row.name||row.campusName||("校区 "+row.id)});});return field("eduCampusId","所属校区",selected,"",false,options);}
  function openTeacherDialog(row){row=row||{};var editing=!!row.userId;var fields=field("realName","教师姓名",row.realName||"")+field("name","登录账号",row.name||"","text")+(!editing?field("password","初始密码","","password"):"")+campusOptions((row.eduCampusIdList||[])[0]||row.eduCampusId)+field("state","任职状态",row.tchState===false?"停用":"在职","",false,[{value:"在职",label:"在职"},{value:"停用",label:"停用"}]);openRecordDialog("teacher",editing?"编辑教师":"新增教师","教师账号",fields,row);}
  function openPasswordDialog(row){var fields=field("password","新密码","","password",true);openRecordDialog("password","重置密码","教师账号 · "+text(row.realName||row.name),fields,row);}
  function openCampusDialog(row){row=row||{};var fields=field("name","校区名称",row.name||row.campusName||"","text",true)+field("address","校区地址",row.address||"","text",true)+field("phone","联系电话",row.phone||"","tel")+field("state","启用状态",row.state===0?"0":"1","",false,[{value:"1",label:"启用"},{value:"0",label:"停用"}]);openRecordDialog("campus",row.id?"编辑校区":"新增校区","校区资料",fields,row);}
  function teacherStatus(row){return row.tchState===false||row.state==="停用"||row.state==="离职"?"停用":"在职";}
  function renderTeacherTable(content){var node=document.getElementById("teacher-table");var rows=(content&&content.records)||[];state.teachers=rows;if(!rows.length){node.innerHTML=empty("暂无教师账号","点击“新增教师”创建第一个授课账号。");return;}node.className="";node.innerHTML='<table class="data-table"><thead><tr><th>教师</th><th>登录账号</th><th>所属校区</th><th>角色</th><th>状态</th><th>操作</th></tr></thead><tbody>'+rows.map(function(row){var status=teacherStatus(row);return '<tr><td><strong>'+escapeHtml(row.realName||row.name)+'</strong></td><td>'+escapeHtml(row.name)+'</td><td>'+escapeHtml(row.eduCampusName||row.campusName||"未分配")+'</td><td>'+escapeHtml((row.roleNameList||[]).join("、")||"机构教师")+'</td><td><span class="status'+(status==="停用"?' is-disabled':'')+'">'+status+'</span></td><td><div class="table-actions"><button type="button" data-teacher-action="edit" data-id="'+row.userId+'">编辑</button><button type="button" data-teacher-action="password" data-id="'+row.userId+'">重置密码</button><button type="button" data-teacher-action="toggle" data-id="'+row.userId+'">'+(status==="停用"?'启用':'停用')+'</button><button type="button" data-teacher-action="delete" data-id="'+row.userId+'">删除</button></div></td></tr>';}).join("")+'</tbody></table>';}
  function loadTeachers(){var node=document.getElementById("teacher-table");node.className="list-state";node.textContent="正在加载教师账号...";var query=document.getElementById("teacher-search").value.trim();return request("/api/workspace/teachers?query="+encodeURIComponent(query)).then(renderTeacherTable).catch(function(error){node.innerHTML=empty("教师账号加载失败",error.message);});}
  function renderCampusTable(content){var node=document.getElementById("campus-table");var rows=(content&&content.records)||[];state.campuses=rows;if(!rows.length){node.innerHTML=empty("暂无校区资料","点击“新增校区”建立教学组织范围。");return;}node.className="";node.innerHTML='<table class="data-table"><thead><tr><th>校区名称</th><th>地址</th><th>教师</th><th>班级</th><th>状态</th><th>操作</th></tr></thead><tbody>'+rows.map(function(row){return '<tr><td><strong>'+escapeHtml(row.name)+'</strong></td><td>'+escapeHtml(row.address||"未填写")+'</td><td>'+escapeHtml(row.teacherCount||0)+' 人</td><td>'+escapeHtml(row.classCount||0)+' 个</td><td><span class="status'+(row.state===0?' is-disabled':'')+'">'+(row.state===0?'停用':'启用')+'</span></td><td><div class="table-actions"><button type="button" data-campus-action="edit" data-id="'+row.id+'">编辑</button><button type="button" data-campus-action="toggle" data-id="'+row.id+'">'+(row.state===0?'启用':'停用')+'</button></div></td></tr>';}).join("")+'</tbody></table>';}
  function loadCampuses(){var node=document.getElementById("campus-table");node.className="list-state";node.textContent="正在加载校区资料...";return request("/api/workspace/campuses").then(function(content){renderCampusTable(content);if(state.data){state.data.campuses=content.records||[];}}).catch(function(error){node.innerHTML=empty("校区资料加载失败",error.message);});}
  function teacherById(id){return (state.teachers||[]).find(function(row){return String(row.userId)===String(id);});}
  function campusById(id){return (state.campuses||[]).find(function(row){return String(row.id)===String(id);});}
  async function saveDialog(event){event.preventDefault();if(event.submitter&&event.submitter.value==="cancel"){document.getElementById("record-dialog").close();return;}var form=new FormData(event.currentTarget);var values={};form.forEach(function(value,key){values[key]=String(value).trim();});var save=document.getElementById("dialog-save");var errorNode=document.getElementById("dialog-error");save.disabled=true;errorNode.textContent="";try{var mode=state.dialog.mode;var record=state.dialog.record||{};if(mode==="teacher"){values.eduCampusIdList=values.eduCampusId?[Number(values.eduCampusId)]:[];values.eduRoleIdList=[1];values.tchState=values.state!=="停用";delete values.eduCampusId;await request(record.userId?"/api/workspace/teachers/"+record.userId:"/api/workspace/teachers",{method:record.userId?"PATCH":"POST",body:JSON.stringify(values)});await loadTeachers();showToast(record.userId?"教师资料已更新":"教师账号已创建");}else if(mode==="password"){await request("/api/workspace/teachers/"+record.userId+"/password",{method:"POST",body:JSON.stringify(values)});showToast("教师密码已重置");}else if(mode==="campus"){values.state=Number(values.state);await request(record.id?"/api/workspace/campuses/"+record.id:"/api/workspace/campuses",{method:record.id?"PATCH":"POST",body:JSON.stringify(values)});await loadCampuses();showToast(record.id?"校区资料已更新":"校区已创建");}document.getElementById("record-dialog").close();}catch(error){errorNode.textContent=error.message;}finally{save.disabled=false;}}
  document.addEventListener("workspace:view",function(event){if(event.detail.view==="teachers"){loadTeachers();}if(event.detail.view==="campuses"){loadCampuses();}});
  document.getElementById("add-teacher").addEventListener("click",function(){openTeacherDialog();});document.getElementById("add-campus").addEventListener("click",function(){openCampusDialog();});document.getElementById("refresh-teachers").addEventListener("click",loadTeachers);document.getElementById("teacher-search").addEventListener("input",function(){window.clearTimeout(this.searchTimer);this.searchTimer=window.setTimeout(loadTeachers,250);});document.getElementById("record-form").addEventListener("submit",saveDialog);
  document.querySelectorAll("[data-dialog-cancel]").forEach(function(button){button.addEventListener("click",function(){document.getElementById("record-dialog").close();});});
  document.getElementById("teacher-table").addEventListener("click",async function(event){var button=event.target.closest("[data-teacher-action]");if(!button)return;var row=teacherById(button.getAttribute("data-id"));if(!row)return;var action=button.getAttribute("data-teacher-action");if(action==="edit"){openTeacherDialog(row);return;}if(action==="password"){openPasswordDialog(row);return;}if(action==="toggle"){try{await request("/api/workspace/teachers/"+row.userId,{method:"PATCH",body:JSON.stringify({state:teacherStatus(row)==="停用"?"在职":"停用",tchState:teacherStatus(row)==="停用"})});await loadTeachers();showToast("账号状态已更新");}catch(error){showToast(error.message);}return;}if(action==="delete"&&window.confirm("确认删除该教师账号？此操作仅允许未关联班级的账号。")){try{await request("/api/workspace/teachers/"+row.userId,{method:"DELETE"});await loadTeachers();showToast("教师账号已删除");}catch(error){showToast(error.message);}}});
  document.getElementById("campus-table").addEventListener("click",async function(event){var button=event.target.closest("[data-campus-action]");if(!button)return;var row=campusById(button.getAttribute("data-id"));if(!row)return;if(button.getAttribute("data-campus-action")==="edit"){openCampusDialog(row);return;}try{await request("/api/workspace/campuses/"+row.id,{method:"PATCH",body:JSON.stringify({state:row.state===0?1:0})});await loadCampuses();showToast("校区状态已更新");}catch(error){showToast(error.message);}});
  document.querySelectorAll(".nav-link,.heading-actions [data-open-view]").forEach(function(link){var href=link.getAttribute("href")||"";var explicit=link.getAttribute("data-open-view");var hash=explicit||(href.indexOf("#")>=0?href.split("#")[1]:"");if(hash){link.addEventListener("click",function(event){event.preventDefault();history.replaceState(null,"","#"+hash);openView(hash);});}});
  document.querySelector(".mobile-menu").addEventListener("click",function(){shell.classList.toggle("menu-open");});
  document.querySelector(".account-button").addEventListener("click",function(){var menu=document.getElementById("account-popover");menu.hidden=!menu.hidden;this.setAttribute("aria-expanded",menu.hidden?"false":"true");});
  window.addEventListener("hashchange",function(){openView(initialView());});
  roleVisibility();openView(initialView());
  request("/api/workspace/bootstrap").then(renderWorkspace).catch(renderLoadError);
  window.WorkspaceApp={request:request,showToast:showToast,escapeHtml:escapeHtml,state:state,openView:openView,loadTeachers:loadTeachers,loadCampuses:loadCampuses,openTeacherDialog:openTeacherDialog,openCampusDialog:openCampusDialog};
}());
